app/domain/SlpFileWriter.js

* Rewrite how we store the pairs so we spend less time looking for the sources in the array
* Update the pairs at the end of the game so users don't have to disconnect and reconnect to auto switch new SceneItems (this is a stopgap until Palakis releases the next version of OBS Websocket that supports better events)
* Update the timer at game end to 700ms and the frame we start on to -60

Update OBS Autoswitch

---

app/app.global.scss
app/components/Console.js
app/components/FileLoader.js
app/components/FileLoader.scss
app/components/GlobalAlert.scss
app/components/PageWrapper.js
app/components/Settings.js
app/components/common/Scroller.js
app/components/common/Scroller.scss
app/components/stats/GameProfile.js
app/components/stats/GameProfile.scss
app/containers/ConsolePage.js
app/containers/FileLoaderPage.js
app/containers/GameProfilePage.js
app/containers/SettingsPage.js

Update: 2nd May
based on feedback from fizzi:
- Scrollbar is now aligned with right edge
- Space below scrollbar on replays menu removed
- Settings and console page now scroll as well
Screens:
=========================
A lot of style changes were made by PrettierJS (e.g double quotes to singles) - It seems to have happened a lot but pretty sure its based off the rules in .prettierrc so I have left them in the PR. Let me know if this is a mistake
- Now works even with global notification (e.g new version message). 
- Sadly still requires some of the same hackery RE checking for notifications
- Tested on replay list + stats screen
- Screenshots below

Headers remain on screen even when scrolling.

---

app/actions/settings.js
app/main.dev.js
package.json
yarn.lock

Working on windows. Updates the paths on start up or if the user selects an ISO.
Partially tested on macOS

Add game directory to Dolphin paths

---

app/components/stats/GameProfile.js

Before these changes, when selecting a game it would show you the previous game profile's header or if there was no previous it would show an empty header while loading, instead of just displaying nothing.
Before:
After:

Hide game profile header while a game is loading

---

app/menu.js

Removed useless Electron stuff and added links for slippi.gg, Discord, and GitHub
Tested on Windows (works fine) and macOS (works fine)

Update App menu bar with more relevant links

---

app/domain/ConsoleCommunication.js
app/domain/ConsoleConnection.js
app/domain/SlpFileWriter.js

This PR adds permissive licensing for certain files in `app/domain`.
It gives the LGPL license to:
* `ConsoleCommunication.js`
* `ConsoleConnection.js`
This allows the code to be linked/bundled in other libraries without enforcing the restrictions of GPLv3, provided no changes were made to the source code.
It gives the MIT license to:
* `SlpFileWriter.js`
The reasoning for the MIT license for the `SlpFileWriter.js` is because the Slippi spec is open and public and allows potentially merging with the existing `slp-parser-js` library released under MIT.

Add permissive licensing

---

app/domain/SlpFileWriter.js

Listen for SceneItemAdded and SceneItemRemoved events that were added in a recent version of OBS-Websocket. Also change the default timeout to 200ms.

Update OBS Websocket defaults and listen for events

---

app/domain/ConsoleConnection.js

Might as well try both if the user set their connection port to default or legacy.

try both ports if port is set to default or legacy

---

.eslintrc
app/actions/fileLoader.js
app/components/FileLoader.js
app/components/FileRow.js
app/components/stats/GameProfile.js
app/components/stats/GameProfile.scss
app/containers/GameProfilePage.js
app/reducers/fileLoader.js

Added buttons for navigating to previous and next matches in replay folder without leaving the stats page. Lifted filtering short/error files from component to redux store level due to have access to file list in GameProfile component.
[Trello](https://trello.com/c/UiHlb8iP/147-navigate-between-games-on-stats-page)

Stats page nav

---

app/components/Console.js
app/domain/ConsoleCommunication.js

Fixes available connections not using a default `isRealTimeMode`.
Set isRealtime to false in `genHandshakeOut`
fixes #55

Fix bad UBJSON due to null isRealTimeMode

---

app/actions/fileLoader.js
app/components/FileLoader.js
app/reducers/fileLoader.js

Fixes #53
The approach taken here is similar to an infinite scroll - we'll lazy-load game rows in chunks of a pre-configured size, whenever we've reached the end of the table that we've already loaded. We use the `Visibility` element to determine whether the element at the end of the table is visible, and then use the callback that is triggered to render another chunk of games.

Performance: Lazy Load Game Rows in Replay Browser

---

app/components/common/PlayerChiclet.js
app/components/stats/GameProfile.js
app/components/stats/GameProfile.scss
app/utils/players.js

Currently, this will display the netplay name and code on the game profile page. On the file list, it displays the code and falls back to the old player name logic if there is no code.
Screenshots (second image using Player 1 and 2 since this is before the update to pass nicknames for players on Dolphin):

Display netplay codes on the app.

---

app/components/FileLoader.js
app/reducers/fileLoader.js

Fixes #61 
Fixes subdirectory navigation after changes in #58.
These changes break save scroll positions - i.e. when we open a game, then navigate back to the replay browser, we will no longer return to the position we were on in the list of replays. This is due to the fact that now, we trigger an action (`STORE_FILE_LOAD_STATE`) upon the first render, and thus `componentDidMount` (which contains the logic to move to a scroll position) occurs before we've rendered the replays

Bugfix: Subdirectories should now work correctly

---

app/components/common/FolderBrowser.js

This is a minor change that adjusts the ordering of subdirectories in the Replay Browser.
Currently, the subdirectories are sorted in the default string ordering - lexicographic. However, most users will naturally expect numeric ordering, which is the default directory ordering for Windows. I am unsure of the default ordering for Unix systems.
Before this change, directories would be ordered "10", "100, "25"
After the change, the order becomes "10", "25", "100"
Before:
After:

Numerically sort subdirectories

---

app/components/FileLoader.js

Fixes https://github.com/project-slippi/slippi-desktop-app/issues/72
Experience changes:
- Scrolling down in the file browser, pressing back, and re-accessing the file browser will no longer scroll a random distance down.
- The position is now properly stored and restored when clicking on a recording's stats and returning to the file loader.

properly store and restore scroll position when viewing recording stats

---

.gitignore

The `.nvmrc` file is used by the popular Node version manager [nvm](https://github.com/nvm-sh/nvm). For instance, if its contents are
```
10.22.0
```
then running `nvm use` from the repo root will switch the Node version to 10.22.0.

Add .nvmrc to .gitignore

---

app/actions/fileLoader.js
app/components/FileLoader.js
app/components/FileLoader.scss
app/components/FileRow.js
app/components/FileRow.scss
package.json
yarn.lock

Fixes #78 
This PR adds the following:
* a "Click to show all" button which allows the showing of games which have been filtered due to being less than 30 seconds
* the ability to reveal a file in the default file explorer when clicking on the file name
The setting is stored in the local component state which means the option to filter/show is reset back to the default (which is to filter) whenever the component is unmounted.

Allow showing of games less than 30 seconds

---

.github/workflows/build.yml
build/afterSignHook.macos.js
build/entitlements.macos.plist
build/load-macos-certs-ci.sh
package.json

Yeah, I know this PR is coming from a weird spot, but it needs access to actions secrets for testing.
Threads various environment variables/electron-bundler configurations for signing and notarizing the application for macOS. This might take a few passes to get correct and should just be squashed when eventually merged.

First pass at signing the desktop app for macOS

---

package.json

Transition to hardened runtime needs this; probably a more restrictive way to do it, can investigate that in the future.

Enable arbitrary loads for auto updater to work on macOS

---

.eslintrc
app/actions/broadcast.js
app/actions/fileLoader.js
app/components/Broadcast.js
app/components/Broadcast.scss
app/components/FileRow.js
app/domain/SpectateManager.js
app/reducers/settings.js
app/utils/settings.js
package.json
yarn.lock

This PR changes the following:
* Shows a hint for where the spectated games will be stored
* Fixes the viewer ID being cleared when changing broadcast tabs
* Defaults the root SLP folder path to the system defaults (`Documents/Slippi` on Windows, and `~/Slippi` otherwise)
* Adjusts hooks to only lint staged changes on commit and lint all files on pre-push

Show where spectator SLP files will be saved

---

app/domain/DolphinManager.js

Mainline dolphin's CLI parsing library disallows multi letter flags, so this works for both and prevents broken launches on Mainline

-hs -> --hide-seekbar

---

src/renderer/store/app/index.ts
src/renderer/store/settings/index.ts

If the file modification time hasn't changed then we can naively skip validating again.

Only validate when necessary

---

.gitignore
src/common/dolphin.ts
src/common/types.ts
src/main/dolphin/index.ts
src/main/dolphin/instance.ts
src/main/dolphin/manager.ts
src/main/dolphin/types.ts
src/main/dolphinManager.ts
src/main/downloadDolphin.ts
src/main/listeners.ts
src/main/spectateManager.ts
src/main/types.ts
src/renderer/components/LoginNotice.tsx
src/renderer/components/PrivateRoute.tsx
src/renderer/containers/Header/UserMenu.tsx
src/renderer/containers/Header/index.tsx
src/renderer/containers/Settings/DolphinSettings.tsx
src/renderer/containers/Settings/index.tsx
src/renderer/containers/SpectatePage/index.tsx
src/renderer/lib/hooks/useLoginModal.ts
src/renderer/store/settings/index.ts
src/renderer/views/HomeView.tsx
src/renderer/views/SettingsView.tsx

This PR adds the following:
* ability to spectate player matches
* protected routes for functions requiring user login
* settings page for configuring Dolphin
* auto-refreshing of players broadcasting (every 30 seconds)
At the moment there is no ability to change the folder where spectate SLP files are stored. That will come later.

Add spectator functionality

---

src/console/consoleRelay.ts
src/console/mirrorManager.ts
src/console/types.ts
src/dolphin/util.ts
src/renderer/containers/Console/AddConnectionDialog.tsx
src/renderer/containers/Console/AddConnectionForm.tsx
src/renderer/containers/Console/SavedConnectionItem.tsx
src/renderer/lib/consoleConnection.ts
src/renderer/lib/validate.ts
src/settings/types.ts

The style on the replay port needs to be fixed.

feat: add back console relay

---

src/renderer/containers/Console/NewConnectionList.tsx
src/renderer/containers/Console/index.tsx

I recall Jas, perhaps jokingly, saying "How do I know it's actually scanning if it there's no animation?".

Add console scanning indicator

---

src/dolphin/manager.ts
src/dolphin/util.ts
src/renderer/containers/Settings/DolphinSettings.tsx
src/renderer/containers/Settings/MeleeOptions.tsx
src/renderer/lib/hooks/useSettings.ts
src/renderer/styles/theme.ts
src/settings/defaultSettings.ts
src/settings/ipc.ts
src/settings/main.ts
src/settings/settingsManager.ts
src/settings/types.ts

feat: ability to set play button functionality

---

src/common/ipc.ts
src/dolphin/ipc.ts
src/dolphin/main.ts
src/dolphin/util.ts
src/main/listeners.ts
src/renderer/components/ConfirmationModal.tsx
src/renderer/containers/QuickStart/ImportDolphinSettingsStep.tsx
src/renderer/containers/Settings/DolphinSettings.tsx
src/renderer/lib/hooks/useApp.ts
src/renderer/lib/hooks/useQuickStart.ts

Lets users import dolphin settings on macOS and Windows. Linux stores settings in a user config dir so we don't need to worry about them.

feat: add import button to DolphinSettings

---

src/main/index.ts

Right now, if the app is closed by clicking the top-left red close button on macOS, it doesn't quit the app. Normally this is the right behavior on macOS, but there's no corresponding menu item to make the window reappear, so this leads to a confusing state.
I'm down to look at the top-level macos menu later if you want, but this is at least slightly less confusing.

Fix (for now): Quit Mac app on all windows closed

---

src/renderer/lib/hooks/useReplays.ts

This PR checks the indexes when shift selecting replays, then flips the array if the user has shift selected a newer replay after an older one.
This means it's possible to queue up vods in chronological order with shift select.

refactor: shift select respects direction

---

src/dolphin/util.ts

Let's not just return the first appimage in any given directory, but use their proper names instead.
A similar check might be favorable in the case of Windows and MacOS (so as not to simply execute "aVirus.Dolphin.exe"), but I'm not familiar with those platforms.

feat: safer find appimage check

---

src/common/ipc.ts
src/main/index.ts
src/main/listeners.ts
src/renderer/lib/hooks/useApp.ts

On macOS, prior to this change creating a new main window after having
closed it would take a few seconds. Forcing this check to the background
and showing the window sooner results in a quicker feeling load process.
I believe this should result in quicker appearance on other platforms as
well, but someone would need to test there.
This can be tested as of this commit by commenting out the `app.quit()`
call on `all-windows-closed`. Combined with some other PRs in the
pipeline it should work as expected.
(A good chunk of this patch was authored by Nikki; I just swapped some
window focus calls and tested on macOS)

Check for updates to background, window sooner (macOS).

---

src/renderer/containers/ReplayBrowser/FileList.tsx
src/renderer/containers/ReplayBrowser/ReplayFile.tsx
src/renderer/lib/hooks/useReplays.ts

This could have further implications for `useMouseTrap`. It seems like under certain conditions, the program may not pick up a key making it a pretty bad choice for managing an "isShiftHeld" state.
In this case, I was activating my ShareX recording software which records the screen by pressing `Shift + PrntScrn`. I was not pressing shift any other time. My guess is because ShareX freezes the screen when taking a screenshot, electron does not pick up the release of the key? May be other scenarios where this can happen though.
https://user-images.githubusercontent.com/1534726/132077505-38455ce4-5170-45ac-9c9c-e320f25dc245.mp4

fix: sticky shift key bug when starting a recording with ShareX

---

src/renderer/components/BouncingSlippiLogo.tsx

https://user-images.githubusercontent.com/1380104/129359530-2b834eda-3f0a-4a93-b352-5510408d7142.mov

Make slippi logo do a barrel roll on hover

---

src/console/autoSwitcher.ts
src/console/workerInterface.ts

This PR attempts to fix 2 known bugs surrounding the auto switcher.
Current Behavior
1. If OBS is not open, attempting to mirror will provide a toast that just says `some stuff [object Object]`, which is useless to the end user
2. If OBS closes while the auto switcher is connected, when the auto switcher triggers the UI will crash.

fix: mirroring failures caused by use of OBS websocket

---

src/dolphin/manager.ts
src/dolphin/util.ts
src/renderer/components/PathInput.tsx
src/renderer/containers/Settings/MeleeOptions.tsx
src/renderer/containers/Settings/ReplayOptions.tsx
src/renderer/lib/hooks/useSettings.ts
src/settings/defaultSettings.ts
src/settings/ipc.ts
src/settings/main.ts
src/settings/settingsManager.ts
src/settings/types.ts

Pushes settings from Launcher to Dolphin when Dolphin is launched. Launcher settings are preferred and used to overwrite Dolphin settings when reasonable (time to launch dolphin is not noticeably affected).
- Replay root directory
- Use monthly subfolders
Users that don't use the Launcher will be able to change their settings as normal. However, if everyone is eventually required to use the Launcher, the ability to change settings via Dolphin should either be removed or synced with the Launcher.

feat: update dolphin settings

---

FAQ.md
src/common/constants.ts
src/dolphin/instance.ts
src/dolphin/ipc.ts
src/dolphin/main.ts
src/dolphin/manager.ts
src/renderer/lib/hooks/useAppListeners.ts

Handles non-zero exit codes when Dolphin closes unexpectedly by showing an error message. Prior to this nothing would happen and the user would have no idea what is happening.
TODO:
1. Test this on other operating systems, make sure closing the application normally doesn't cause errors messages.
2. Improve copy?
Improvements:
1. Make it so that if the error code detected is related to missing DLLs, direct the user to a download link for VCR
2. Perhaps increase the prominence of the error

fix: show error when dolphin is missing dlls

---

.eslintrc.js
.github/workflows/build.yml
jest.config.js
package.json
src/renderer/containers/ActivateOnlineForm.tsx
src/renderer/containers/Console/AddConnectionForm.tsx
src/renderer/containers/Header/NameChangeDialog.tsx
src/renderer/lib/validate.spec.ts
src/renderer/lib/validate.ts
yarn.lock

The backend and website include the same validation.

feat: client side display name validation

---

src/common/exists.ts
src/renderer/containers/ReplayBrowser/ReplayBrowser.tsx
src/renderer/lib/hooks/useReplays.ts
src/renderer/lib/utils.ts
src/replays/loadFolder.ts
src/replays/types.ts

This PR introduces the calculation of total folder size and shows it in the replay browser in a human readable format. It introduces no dependencies. 
This allows players to get a better idea of how much space their replays are taking.

Show total folder size in replay browser

---

src/dolphin/checkVersion.ts
src/dolphin/downloadDolphin.ts
src/dolphin/manager.ts
src/dolphin/types.ts
src/renderer/lib/slippiBackend.ts
webpack.main.additions.js

Swaps our current implementation of querying github in favor of the getLatestDolphin query on our backend.
The refactor of `downloadDolphin.ts` does reorder a bit of the code so the diff is a bit greater there.

feat: leverage slippi backend's getLatestDolphin query

---

src/dolphin/types.ts
src/renderer/containers/Header/UserInfo.tsx
src/renderer/containers/Header/UserMenu.tsx
src/renderer/containers/Header/index.tsx
src/renderer/lib/hooks/useAccount.ts
src/renderer/lib/hooks/useApp.ts
src/renderer/lib/hooks/useQuickStart.ts
src/renderer/lib/slippiBackend.ts

Previously when the user had no internet access or Slippi servers were down we would show the online activation step which was pretty confusing to users.
New behavior:
https://user-images.githubusercontent.com/1534726/153937946-e748898c-87fd-4f17-a0fc-5bd83fbbaacb.mp4

feat: add better handling when play key fails to fetch

---

src/renderer/App.tsx
src/renderer/components/AuthGuard.tsx
src/renderer/components/PrivateRoute.tsx
src/renderer/containers/ReplayBrowser/ReplayBrowserPage.tsx
src/renderer/views/MainView.tsx
src/renderer/views/SettingsView.tsx

This PR migrates some of the route related components to be closer to the React Router v6 API. This will make it easier for the react-router upgrade in the future.
For more info on these changes, see: https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v51

refactor: prepare react router routes for v6 upgrade

---

src/dolphin/ipc.ts
src/dolphin/main.ts
src/renderer/lib/slippiBackend.ts

in the future we want to be a bit more tolerant about slippi being in a partially down state. to handle matchmaking without the DB or firebase we need to use the details from the user.json so we should keep the file up to date.

feat: overwrite play key file if they don't match

---

src/common/types.ts
src/main/listeners.ts
src/renderer/containers/QuickStart/IsoSelectionStep.tsx
src/renderer/containers/Settings/MeleeOptions.tsx
src/renderer/lib/hooks/useAppListeners.ts
src/renderer/lib/hooks/useIsoVerification.ts

adds an `Unvalidated` state for ISOs so that we don't immediately assume the ISO is invalid and show the error

fix: showing invalid toast immediately on drop

---

src/renderer/lib/hooks/useAppListeners.ts
src/renderer/lib/utils.ts

I'm on the fence about how I rewrote this. maybe nested switch statements are bad design, but it does make it easier to add new error codes.

refactor: switch case the error codes and add some new ones

---

.erb/configs/webpack.config.renderer.dev.dll.ts
package.json
src/renderer/services/auth/auth.service.ts
yarn.lock

This PR upgrades the `firebase` dependency from version 8 to version 9, allowing us to take advantage of tree-shaking, reducing the renderer bundle size by around 730KB. 
The `firebase` dependency seems to have an issue with ERB's postinstall script, so we just ignore it in the `renderer.dev.dll` webpack config. It seems to work fine.

Upgrade firebase from v8 to v9

---

package.json
src/renderer/App.tsx
src/renderer/components/CustomToast.tsx
src/renderer/components/MultiPathInput.tsx
src/renderer/components/ToastProvider.tsx
src/renderer/containers/ActivateOnlineForm.tsx
src/renderer/containers/Console/SavedConnectionItem.tsx
src/renderer/containers/Console/index.tsx
src/renderer/containers/Header/ActivateOnlineDialog.tsx
src/renderer/containers/Header/NameChangeDialog.tsx
src/renderer/containers/Header/index.tsx
src/renderer/containers/QuickStart/ImportDolphinSettingsStep.tsx
src/renderer/containers/QuickStart/IsoSelectionStep.tsx
src/renderer/containers/ReplayBrowser/FilterToolbar.tsx
src/renderer/containers/ReplayBrowser/ReplayBrowser.tsx
src/renderer/containers/Settings/AdvancedAppSettings.tsx
src/renderer/containers/Settings/BuildInfo.tsx
src/renderer/containers/Settings/SupportBox.tsx
src/renderer/containers/SpectatePage/ShareGameplayBlock/index.tsx
src/renderer/lib/hooks/useApp.ts
src/renderer/lib/hooks/useAppListeners.ts
src/renderer/lib/hooks/useBroadcastList.ts
src/renderer/lib/hooks/useDolphin.ts
src/renderer/lib/hooks/useFileDrag.ts
src/renderer/lib/hooks/useInstallAppUpdate.ts
src/renderer/lib/hooks/useToasts.ts
yarn.lock

This PR replaces the usage of the no-longer-maintained [`react-toast-notifications`](https://www.npmjs.com/package/react-toast-notifications) with the MUI endorsed `notistack`. We need to use the v3.alpha version of [`notistack`](https://github.com/iamhosseindhv/notistack/tree/alpha) since v2 doesn't have an easy way of overwriting the toast style. Honestly not too sure if using an alpha library is better or worse than an unmaintained library. ¯\\\_(ツ)\_/¯
We also introduce our own `useToasts` hook to make future toast library changes simpler. Future toast changes should only need to update the `useToasts.ts` and `ToastProvider.tsx` files instead of all files that emit toasts.

Replace react-toast-notifications with notistack

---

src/renderer/containers/ReplayFileStats/GameProfileHeader.tsx
src/renderer/containers/ReplayFileStats/TableStyles.tsx
src/renderer/containers/ReplayFileStats/index.tsx

This PR makes the background stage image occupy the entire stats page. AKA it makes the stats page purty.

Use full screen background image in stats page

---

src/broadcast/broadcast.worker.interface.ts
src/broadcast/broadcast.worker.ts
src/broadcast/install.ts
src/broadcast/spectate.worker.interface.ts
src/broadcast/spectate.worker.ts
src/console/install.ts
src/console/mirror.worker.interface.ts
src/console/mirror.worker.ts
src/replays/install.ts
src/replays/replays.worker.interface.ts
src/replays/replays.worker.ts
src/utils/registerWorker.ts

This PR refactors the workers to only be spawned when necessary.
Most players will rarely need console mirroring, or broadcast/spectate features so always spawning those workers on app launch is 1. wasting resources, 2. increasing app startup time.
We now only spawn the workers when we actually need to. We also move the common worker registration logic to `src/utils/registerWorker.ts` to automatically terminate the workers on app quit.
The purpose of the `src/utils` folder is to hold functions that are imported across the different main modules since ideally modules should not import from `src/main`.

Only spawn workers when needed

---

src/dolphin/install/installation.ts

Users should still be able to access Dolphin related features as long as the executable is available.

fix: dolphin never getting to ready state if offline

---

src/dolphin/install/installation.ts

this avoids a certain case where dolphin decides to spit out more than the version, most likely to happen on linux due to other libs writing to stdout.

fix/feat: use regex to find the dolphin version

---

src/dolphin/install/fetchLatestVersion.ts
src/renderer/containers/SpectatePage/ShareGameplayBlock/StartBroadcastDialog.tsx
src/renderer/services/slippi/slippi.service.ts

retryLink is fairly straightforward so I won't explain it.
errorLink gives us some more context about failures, but throwing in that function causes really weird experiences. I can look into it further, but I'm not sure if we will gain much by throwing in there.
`setContext` is the interesting link, it essentially replaces the old `_refreshAuthToken` by handling the authn at the time of request rather than manually before a request.
Docs (it is short, I promise): https://www.apollographql.com/docs/react/api/link/apollo-link-context/
We can then combine all these links together and the apollo client will use them when necessary.

feat: handle auth, errors, and retry with links

---

.erb/scripts/installer.nsh

This PR fixes #327.
After extensive googling, it turns out [we can actually register custom URL scheme protocols without Admin](https://stackoverflow.com/questions/29509624/can-i-register-a-custom-url-scheme-without-administrator-elevation) as long as we use `HKCU\Software\Classes` instead of using `HKCR`.
The only thing left was to figure out how to conditionally write the registry based on which install mode was currently in use -- current user or all users. After having no luck with `$MultiUser.InstallMode`, [this comment](https://github.com/electron-userland/electron-builder/issues/3319#issuecomment-804344631) revealed that we can simply use `$installMode` for the conditional.

Fix slippi protocol not registering when installing for current user

---

src/renderer/containers/ReplayBrowser/ReplayFile.tsx

This PR fixes the MacOS graphical issue when selecting a replay file which was discovered after bumping Electron version to v19.
This bug may be related to [this open issue](https://bugs.chromium.org/p/chromium/issues/detail?id=961581) or [this closed issue](https://bugs.chromium.org/p/chromium/issues/detail?id=503638) in Chromium's bug tracker. In any case it's likely got something to do with `mix-blend-mode: color-dodge;` and how it interacts with `transform` or `transition` changes. Not too sure why but disabling this opacity transition makes this bug not appear for now -- but perhaps there may be other triggers that cause this bug to reappear. It will be good to continue monitoring this issue especially on MacOS in the future after changes to `ReplayFile.tsx`. …

Fix MacOS graphical bug after bumping to Electron version 19

---

.github/workflows/build.yml

uses electron-builder's built in signing functionality like we do for macOS

ci: sign windows exe

---

jest.config.js
package.json
release/app/package.json
release/app/yarn.lock
src/console/autoSwitcher.ts
src/console/mirrorManager.ts
src/console/types.ts
src/renderer/containers/Console/AddConnectionDialog.tsx
src/renderer/containers/Console/AddConnectionForm.tsx
src/renderer/containers/Console/SavedConnectionItem.tsx
src/renderer/lib/validate.ts
src/settings/types.ts
yarn.lock

So the autoswitcher works with OBS 28+.
Still need to test with 2 PCs.

Update for OBS Websocket 5.0

---

src/renderer/containers/Console/OBSWebsocketNotice.tsx
src/renderer/containers/Console/index.tsx

uses localstorage to ensure it only shows once. this should help avoid users getting confused about the change.

feat: add notice about OBS websocket update

---

src/renderer/containers/Header/UserMenu.tsx

This PR adds 'View profile' to the user menu. Clicking this button opens up the browser to their `slippi.gg/user/connectcode-number` page.
While we're add it we also update the logout icon to be a proper logout icon. Not sure when the `LogoutIcon` was added but that option didn't exist when the menu was first conceived.

Add 'View profile' menu item

---

src/main/preload.ts
src/renderer/components/MultiPathInput.tsx
src/renderer/lib/utils.ts
src/replays/folderTreeService.ts
src/utils/isSubdirectory.ts

Resolves #359
Previously, attempting to add an additional SLP directory that:
1. was adjacent to the root SLP directory
2. in its name, contained a substring of the root SLP directory name
...would result in a `Cannot add sub directories of the Root SLP Directory` error. 
e.g.
Root = `C:\Users\Nikki\Documents\Slippi`
Adding `C:\Users\Nikki\Documents\Slippi Test` causes an error.
This was occurring because the previous SLP directory path validation used [`includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) to check whether the new path was a subdirectory of the root path.
This PR fixes the issue by leveraging an existing utils function that checks whether a folder is a subdirectory of another.
- Create a directory adjacent to the …

fix: extend SLP directory path validation to be more robust

---

src/main/main.ts

Fixes #366.
This is one of the ways to fix this, there are others that may be preferable (such as doing `preventDefault` on title changes in the main process). If you'd like a different approach (or to pull this title from the product name during the webpack build or something), let me know, happy to change it!

Prevent Electron window title changes resulting from navigation.

---

src/dolphin/install/installation.ts
src/dolphin/manager.ts
src/dolphin/types.ts
src/renderer/components/Footer.tsx
src/renderer/components/PersistentNotification.tsx
src/renderer/containers/Header/index.tsx
src/renderer/lib/dolphin/useDolphinActions.ts
src/renderer/lib/dolphin/useDolphinListeners.ts
src/renderer/lib/dolphin/useDolphinStore.ts
src/renderer/lib/hooks/useAppUpdate.ts

The slippi logo in the top right is repurposed to be a check for updates button. failures during an update aren't handled atm.

feat: add check for updates button

---

src/dolphin/api.ts
src/dolphin/ipc.ts
src/dolphin/setup.ts
src/dolphin/types.ts
src/main/main.ts
src/main/menu.ts
src/renderer/containers/Settings/DolphinSettings.tsx
src/renderer/lib/dolphin/useDolphinActions.ts

Swap the `Open containing folder` with `Open settings folder` which opens the correct location for where the User settings are stored on each OS. for windows this is just where dolphin is located, but on macOS/linux it is a separate config folder.

feat: add button to open dolphin settings folder 

---

src/renderer/containers/ReplayBrowser/replay_file/ReplayFile.container.tsx
src/renderer/lib/matchNames.ts

This PR fixes the issue where some replays will show up with empty names. This is because in some cases, we check against null instead of an empty string `''`.
Solution: We return empty string by default instead of null when extracting player names.

Fix empty player names in replay browser

---

src/dolphin/install/installation.ts
src/dolphin/install/macos.ts

This updates the Launcher to use the macOS `User` folder path(s) specified in [Ishiiruka/#374](https://github.com/project-slippi/Ishiiruka/pull/374).
The gist of this is that it appears that Ventura actually enforces signed bundles not being altered, and coupled with GateKeeper checking on each open as opposed to the first open, means that users get a message saying the app is damaged due to `Dolphin.ini`.
As far as I can tell this is the only core part that needs to be altered, and I went ahead and just mostly copied the approach the Linux block uses - but I defer to y'all.

macOS: Mirror updated paths in Ishiiruka/374

---

src/dolphin/config/config.ts
src/dolphin/install/installation.ts
src/dolphin/manager.ts
src/renderer/containers/Settings/MeleeOptions.tsx
src/renderer/lib/hooks/useSettings.ts
src/settings/api.ts
src/settings/defaultSettings.ts
src/settings/ipc.ts
src/settings/settingsManager.ts
src/settings/setup.ts
src/settings/types.ts

This will allow users to enable the jukebox from the launcher. Additionally i added syncing settings back from dolphin on close

feat: update relevant settings from imported ini and add jukebox toggle

---

src/dolphin/config/config.ts
src/dolphin/manager.ts

i've removed syncing settings from the playback dolphin because i realized it is unnecessary which immediately fixes the issue when closing dolphin

fix: don't update settings from playback dolphin and check if update is necessary

---

.erb/scripts/windows-sign.js
.github/workflows/build.yml
.gitignore
electron-builder.json

the gist of it is that signing keys now need to be stored in HSMs which means we won't have the signing cert available for electron-builder to do its thing. instead we have a custom script for signing that will handle calling CodeSignTool for each file that needs to be signed.
this will only sign release commits because we have to pay a service to manage our HSM. i hate this whole situation

ci: fix windows code signing

---

package.json
src/utils/ipc.ts
yarn.lock

This PR reverts Electron back to v19 but to the [latest version of Electron v19 when it hit EOL](https://github.com/electron/electron/releases/tag/v19.1.9) back in Dec 2022.
We do this because it breaks the database initiatives with `better-sqlite3`. We'll revert for now and figure out the best way forward after the database work has been merged.
We noticed that the [app crashes when typing into the electron browser window console](https://github.com/electron/electron/issues/34350). This is fixed in newer versions of Electron so we updated the Electron dependency in #394.
However, we noticed that after updating the Electron version, the database intiatives (e.g. #384) no longer work. There is currently some momentum in getting the database work into the codebase so we revert this …

deps: revert Electron back to v19

---

package.json
src/renderer/lib/hooks/use_toasts.ts
src/renderer/services/install.ts
src/renderer/services/notification/notification.service.ts
src/renderer/services/notification/types.ts
src/renderer/services/types.ts
yarn.lock

Currently we can only show notifications by using the `useToasts()` hook inside a React component. This PR allows us to show notifications outside of a React component logic by introducing a `NotificationService`.

Add notification service

---

src/broadcast/broadcast_manager.ts
src/broadcast/spectate_manager.ts
src/dolphin/instance.ts
src/dolphin/setup.ts
src/renderer/app/header/header.tsx
src/renderer/components/dual_pane.tsx
src/renderer/pages/replays/replay_browser/file_list.tsx
src/renderer/pages/replays/replay_browser/replay_file/replay_file.container.tsx
src/renderer/pages/replays/replay_file_stats/game_profile.tsx
src/renderer/pages/replays/replay_file_stats/game_profile_header.tsx
src/renderer/pages/replays/replay_file_stats/kill_table.tsx
src/renderer/pages/replays/replay_file_stats/overall_table.tsx
src/renderer/pages/replays/replay_file_stats/punish_table.tsx
src/renderer/pages/replays/replay_file_stats/replay_file_stats.tsx
src/renderer/pages/settings/chat_settings/chat_messages_input.tsx
src/renderer/pages/settings/chat_settings/use_chat_messages.ts
src/replays/file_system_replay_provider/replays.worker.ts

Importing `lodash` with `import _ from "lodash"` imports the entire `lodash` library, even if only a subset of the functions are used. In addition to this, unused lodash imports are not caught by the linter since it is excluded from the unused checks since it is prefixed with `_`.
This PR does the following:
* makes all `lodash` imports explicit by changing them to be `import func from "lodash/func"`
* removes all usages of lodash's `_.chain()` function since it also needs to import all lodash functions.
* removes some lodash usages with ES6 built-ins like `filter`
This reduces our lodash import from 71 KB down to 2.9 KB and reduces our `renderer.js` bundle from 1.13 MB  down to 1.06 MB (-5%).

refactor: use explicit lodash imports

---

.erb/configs/webpack.config.base.ts
.erb/configs/webpack.config.renderer.prod.ts
package.json
src/console/connection_scanner.ts
src/renderer/containers/build_info.tsx
src/renderer/lib/time.ts
src/renderer/pages/home/news_feed/news_article/news_article.tsx
src/renderer/pages/replays/replay_browser/replay_file/replay_file.container.tsx
src/renderer/pages/replays/replay_file_stats/game_profile_header.tsx
src/renderer/pages/spectate/share_gameplay_block/broadcast_panel.tsx
src/replays/database_replay_provider/infer_start_time.ts
src/replays/file_system_replay_provider/load_file.ts
yarn.lock

This PR removes the deprecated `moment` dependency in favour of a lighter package `date-fns`.
This reduces our package bundle size by around 30KB, from 1.06MB to 1.03MB.

refactor: remove moment dependency

---

src/renderer/pages/home/sidebar/tournament_links.tsx

this start.gg filter seems to be not entirely reliable. At time of commit, [https://www.start.gg/tournament/40-kurobra40](https://www.start.gg/tournament/40-kurobra40) is filtered out even though registration is still very much open (though most events are capped)
it seems best to me to not falsely filter any tournaments that may actually still have reg open

Remove 'reg open' filter from 'Nearby Tournaments' URL

---

src/broadcast/broadcast_manager.ts

- remove unnecessary newFirstEvent check in broadcast reconnect
- add retry logic while connecting/reconnecting
#427

fix: attempt to fix dangling broadcasts

---

FAQ.md
src/main/preload.ts
src/renderer/components/markdown_content/code_block.tsx
src/renderer/components/markdown_content/markdown_content.tsx
src/renderer/pages/home/news_feed/news_article/news_article.tsx
src/renderer/pages/settings/dolphin_settings/gecko_codes/manage_codes/manage_codes.container.tsx
src/renderer/pages/settings/help_page/help_page.tsx
src/renderer/pages/settings/help_page/network_diagnostics/cgnat_command_section.tsx
src/renderer/pages/settings/help_page/network_diagnostics/nat_type_section.tsx
src/renderer/pages/settings/help_page/network_diagnostics/network_diagnostics_result.tsx
src/renderer/pages/spectate/share_gameplay_block/start_broadcast_dialog.tsx
src/renderer/pages/spectate/spectator_id_block.tsx

This PR adds proper code block functionality to our markdown renderer. A copy to clipboard button appears on hover. We also replace the usages of our electron clipboard with built in browser clipboard functionality.

Add copy to clipboard functionality to code blocks

---

src/dolphin/install/ishiiruka_installation.ts
src/dolphin/install/mainline_installation.ts
src/renderer/lib/hooks/use_app.ts

i just don't think we need to delete the dolphin archives immediately, moving it to on startup seems fairly sane

refactor: remove temp files on startup
