project-slippi/slippi-launcher

- app/actions/console.js
- app/components/Console.js
- app/components/Console.scss
- app/domain/ConsoleConnection.js
- app/reducers/console.js
> [PR] Add disconnect button - start work on reconnect

- app/components/Console.js
- app/components/Console.scss
- app/domain/ConsoleConnection.js
- app/domain/SlpFileWriter.js
My proposed relay solution. It is a simple relay that supports ~~a single client~~ multiple clients to be connected. It simply passes on all data from the wii to the clients connected on port `connectionId + 666`.
I also fixed the issue of panes only being rendered when they are active.
> Internal Relay

- app/actions/fileLoader.js
- app/components/FileLoader.js
- app/components/FileLoader.scss
- app/components/FileRow.js
- app/components/FileRow.scss
- app/domain/DolphinManager.js
this lets you playback a whole set at once, etc.
also paves the way to do other batch operations if wanted (delete, star, relabel, etc.)
> Add ability to select multiple files to queue for dolphin playback

- app/components/Console.js
- app/domain/SlpFileWriter.js
This fixes the issue on Mac/Linux where binding to ports < 1024
require sudo privileges.
> Bump relay port to start at 1666.

- package.json
> node-sass update

- app/components/stats/KillsTable.js
> Fixed issue #38, added grab release

- app/actions/settings.js
- app/components/Settings.js
- app/components/Settings.scss
- app/components/common/ActionInput.js
- app/domain/DolphinManager.js
- app/main.dev.js
- app/reducers/settings.js
Also cleans up the code that adds the game path to dolphin by moving the bit of code to dolphin manager.
[Video of reset in action](https://streamable.com/4nnbe)
> Reset Dolphin Button

- README.md
The dolphin instructions were a bit unclear and did not mention the overwrite folder.
> Update README Dolphin Instructions

- app/actions/fileLoader.js
- app/components/FileRow.js
- app/components/stats/GameProfile.js
- app/containers/GameProfilePage.js
- app/main.dev.js
- app/utils/time.js
Fixes #73 
Also adds support for inferring from filename in case the file was copied or downloaded from another machine, which would affect ctime
> Unknown time fix

- app/main.dev.js
This PR's goal is to fix the bug where when people install a new version of the desktop app, the old Dolphin cannot be replaced because it was created with elevated permissions itself.
Note: it is ideal if we do not ALSO copy the newer Dolphin with elevated permissions such that we can avoid having to worry about this issue in the future.
This bug would cause the following output when installing 1.5.0:
Here are the repro steps:
1) Set User Account Control to the default value (one from the top)
2) Uninstall the Slippi Desktop App if you have it installed
3) Go to the Desktop App AppData folder `C:\Users\<user>\AppData\Roaming\Slippi Desktop App` and delete the `dolphin` folder
4) Install v1.4.5 of the desktop app: https://github.com/project-slippi/slippi-desktop-app/releases/download/v1.4. …
> [PR] [Windows] Elevate permissions before deleting old Dolphin

- app/domain/SlpFileWriter.js
- package.json
- yarn.lock
This PR uses the `SlpFileWriter` from the `slippi-js` package to automatically generate SLP files.
> Simplify SLP file writing code

- app/domain/SlpFileWriter.js
readPos is useless honestly. We can just send the relay all previous data from the current game when it connects (if it connects during a game) and then send it each piece of new data rather than concating (EXPENSIVE) and splicing (why would you concat and then splice?)
also remove the MIT license because it isn't necessary anymore, the code from this file that needed to be MIT is now LGPL in slippi-js
> Attempt to fix performance issue from relaying

- app/actions/fileLoader.js
- app/components/FileLoader.js
There is now a "delete" button when you select files.
> Add Delete Button to selection menu

- app/components/stats/OverallTable.js
> Add ledgegrab count to actions and digital inputs per second in stats

- app/actions/fileLoader.js
- app/components/stats/GameProfile.js
- app/components/stats/GameProfile.scss
- app/components/stats/PunishesTable.js
- app/domain/DolphinManager.js
- package.json
sorry for the random black frames, OBS was acting strangely whenever dolphin opened during recording...
> Make Conversion Timestamps Play Replay from that conversion

- src/common/dolphin.ts
- src/main/dolphin/manager.ts
- src/main/downloadDolphin.ts
- src/main/listeners.ts
- src/renderer/containers/Settings/DolphinSettings.tsx
- src/renderer/containers/Settings/index.tsx
- src/renderer/store/settings/index.ts
- src/renderer/views/SettingsView.tsx
There is a bit of clean up around installDolphin because I realized we don't need to back up the User folder/user.json for Windows. I need to test on macOS though.
> Add Dolphin Settings

- src/dolphin/ipc.ts
- src/dolphin/main.ts
- src/renderer/containers/ReplayFileStats/KillTable.tsx
- src/renderer/containers/ReplayFileStats/PunishTable.tsx
- src/renderer/store/replays/index.ts
> Add "Play from here" to kill/punish tables

- package.json
- src/renderer/containers/ReplayFileStats/GameProfile.tsx
- src/renderer/containers/ReplayFileStats/KillTable.tsx
- src/renderer/containers/ReplayFileStats/OverallTable.tsx
- src/renderer/containers/ReplayFileStats/PunishTable.tsx
- src/renderer/containers/ReplayFileStats/index.tsx
- src/renderer/store/replays/index.ts
- src/replays/ipc.ts
- src/replays/main.ts
- src/replays/worker.ts
- yarn.lock
* Updated slippi-js to 6.1.1
* Added L-Cancel count to the overall stats view
* fixed kills and punish tables
> Update slippi-js and fix issues that arose

- src/renderer/containers/ReplayBrowser/FileList.tsx
- src/renderer/containers/ReplayBrowser/FileSelectionToolbar.tsx
- src/renderer/containers/ReplayBrowser/ReplayFile.tsx
- src/renderer/containers/ReplayBrowser/index.tsx
- src/renderer/store/replays/index.ts
Fixes #155 
Styles are temporary.
Functionality needs to be added still to "Play All" and "Delete" buttons
> Add multiselect to replay browser

- package.json
- src/dolphin/downloadDolphin.ts
- src/dolphin/instance.ts
- src/dolphin/manager.ts
- src/dolphin/util.ts
- src/renderer/containers/Console/SavedConnectionItem.tsx
- src/renderer/containers/ReplayBrowser/index.tsx
- src/renderer/containers/Settings/DolphinSettings.tsx
- src/renderer/containers/SpectatePage/index.tsx
- yarn.lock
> Fix downloading and launching Dolphin on macOS

- src/renderer/containers/ActivateOnlineForm.tsx
- src/renderer/containers/Header/ActivateOnlineDialog.tsx
- src/renderer/containers/Header/UserMenu.tsx
- src/renderer/containers/QuickStart/ActivateOnlineStep.tsx
- src/renderer/lib/slippiBackend.ts
- src/renderer/lib/validate.ts
UI needs some work, but the functionality is there.
> feat: integrated online enabler

- package.json
- src/console/mirrorManager.ts
- src/console/types.ts
- src/renderer/components/FormInputs/Toggle.tsx
- src/renderer/components/IconMenu.tsx
- src/renderer/containers/Console/AddConnectionDialog.tsx
- src/renderer/containers/Console/AddConnectionForm.tsx
- src/renderer/containers/Console/SavedConnectionItem.tsx
- src/renderer/containers/Console/SavedConnectionsList.tsx
- src/renderer/containers/Console/index.tsx
- src/renderer/lib/consoleConnection.ts
- src/settings/types.ts
- yarn.lock
* make mirror settings viewable even when connected so streamers can verify that the settings are correct without disconnecting from the wii.
* add the console nick to the folder path
* ![image](https://user-images.githubusercontent.com/6331403/135179032-fbf14578-ad52-438a-bd98-c07ecad6d591.png)
> feat: mirroring QoL improvements

- build/installer.nsh
- electron-builder.json
- package.json
- src/main/listeners.ts
Example of the new/fixed flow:
https://user-images.githubusercontent.com/6331403/136672821-17d2502f-ca99-4a12-ac16-104453d62e3f.mp4
> fix: installer and non-silent updater

- src/dolphin/downloadDolphin.ts
- src/renderer/lib/hooks/useApp.ts
plus some other safety changes.
> fix: multiple downloads and installs causing failures on macOS

- src/common/ipc.ts
- src/main/index.ts
- src/main/listeners.ts
- src/renderer/containers/Settings/AdvancedAppSettings.tsx
- src/renderer/containers/Settings/LauncherOptions.tsx
- src/renderer/containers/Settings/index.tsx
- src/renderer/lib/hooks/useSettings.ts
- src/settings/defaultSettings.ts
- src/settings/ipc.ts
- src/settings/main.ts
- src/settings/settingsManager.ts
- src/settings/types.ts
Adds ability to toggle auto updates for the launcher and to clear the temp folder (mostly for support purposes).
> feat: launcher options

- src/broadcast/api.ts
- src/broadcast/types.ts
- src/console/api.ts
- src/console/types.ts
- src/renderer/containers/Console/SavedConnectionItem.tsx
- src/renderer/containers/Console/index.tsx
- src/renderer/containers/SpectatePage/index.tsx
- src/renderer/lib/consoleConnection.ts
- src/renderer/lib/hooks/useAppListeners.ts
- src/renderer/lib/hooks/useBroadcast.ts
- src/renderer/lib/hooks/useBroadcastList.ts
- src/renderer/services/installMockServices.ts
- src/renderer/services/installServices.ts
- src/renderer/services/types.ts
This PR introduces the BroadcastService and the ConsoleService. We will introduce mocking in a later PR, for now it just returns the prod services.
> Add broadcastService and consoleService

- src/renderer/components/BouncingSlippiLogo.tsx
smooths out the animation and gives it a bit of gravity.
https://user-images.githubusercontent.com/6331403/160763210-97480e89-435b-4e0e-96ce-eaa243b6bc40.mp4
https://user-images.githubusercontent.com/6331403/160763291-f935aafa-f57d-471e-88bd-5f57126dad8e.mp4
Storybooks are very cool, thanks vince.
> feat: improve bouncing logo animation

- src/broadcast/spectate.worker.interface.ts
- src/broadcast/spectate.worker.ts
- src/broadcast/spectateManager.ts
- src/console/mirror.worker.interface.ts
- src/console/mirror.worker.ts
- src/console/mirrorManager.ts
- src/console/types.ts
- src/dolphin/types.ts
- src/renderer/containers/Console/SavedConnectionItem.tsx
dolphin will take the name and write to the window to make it easier for streamers to identify which dolphin instance is which.
> feat: pass consoleNick or broadcaster connect code to comm file when spectating

- package.json
- src/dolphin/install/installation.ts
- src/utils/download.ts
- yarn.lock
This PR adds `wget-improved` as a dependency for more verbose download handling. It supports handling of infinite redirects, auto unzipping and more. Hopefully utilising this dependency can fix our intermittent download issues.
> Use wget-improved for better download handling

- package.json
- yarn.lock
need to test on macOS and linux
> deps: upgrade electron to 19.0.10

- src/renderer/containers/Console/index.tsx
simple little dialog for showing some help info about mirroring
> feat: add help/info dialog for mirroring

- src/dolphin/playkey.ts
should only need to merge right before we release the next netplay dolphin build.
> feat: write user.json to new location for win/unix

- src/dolphin/api.ts
- src/dolphin/ipc.ts
- src/dolphin/manager.ts
- src/dolphin/setup.ts
- src/dolphin/types.ts
- src/renderer/containers/Settings/DolphinSettings.tsx
- src/renderer/lib/dolphin/useDolphinActions.ts
- src/renderer/services/dolphin/dolphin.service.mock.ts
Replace `Clear Cache` with `Soft Reset` and rename `Reset everything` to `Hard Reset`. Soft Reset is just a reinstall without removing user settings, apart from clearing the cache.
I did mess with the UI a bit, both of the reset options have indicators so I made the buttons wider to ensure they don't change size when the indicator shows up.
> feat: soft reset

- .erb/scripts/installer.nsh
gives users a prompt to delete the config files/Slippi Dolphin if they want.
closes #348
closes #344
> feat: ask if users want to delete config files

- src/renderer/containers/QuickStart/VerifyEmailStep.tsx
before I think people were clicking the button without reading and having no idea whats going on when the step wasnt progressing
> feat: add error when email not yet verified

- src/renderer/containers/ReplayBrowser/ReplayFile.tsx
- src/replays/loadFile.ts
- src/replays/types.ts
just enabling what vince already setup
> feat: show winners in replay browser

- .eslintrc.js
- src/dolphin/api.ts
- src/dolphin/config/geckoCode.ts
- src/dolphin/ipc.ts
- src/dolphin/setup.ts
- src/dolphin/types.ts
- src/dolphin/util.ts
- src/renderer/containers/Settings/DolphinSettings.tsx
- src/renderer/containers/Settings/GeckoCodes.tsx
- src/renderer/lib/dolphin/useDolphinActions.ts
- src/renderer/services/dolphin/dolphin.service.mock.ts
This PR aims to implement various functions of interacting with Gecko Codes to cover #177
Obsoletes #201 which is out of date
<hr>
Feature List
- Default codes can be disabled but not deleted
<hr>
Polishing TODO
- Suggestions very welcome
> Add Gecko Code handling

- src/renderer/components/ChatMessagesInput.tsx
- src/renderer/components/FormInputs/Button.tsx
- src/renderer/containers/Settings/ChatOptions.tsx
- src/renderer/services/slippi/mockSlippiDataUtils.ts
- src/renderer/services/slippi/slippi.service.mock.ts
This PR changes the following:
* fixes buttons being a weird colour after upgrading the `@mui/material` package
* mocks the chat message functions in mock Slippi service
* adds a login notice to the chat options settings page when a user is not logged in (previously it will get stuck on "Loading..." forever)
* replaces the "Loading..." text with a spinner in the Chat options page.
> Fix button color and add mock chat messages to mock Slippi service

- src/renderer/pages/home/HomePage.tsx
- src/renderer/pages/home/StartggLinks.tsx
- src/renderer/pages/home/TournamentLinks.tsx
- src/renderer/styles/images/startgg-logo.svg
> Add links to nearby and online tournaments in the home page

- .erb/scripts/notarize.js
- package.json
- yarn.lock
- update @electron/notarize
- explicitly set tool in notarize config
> chore(ci): update macos notarization config

- src/main/bluesky.ts
- src/main/news_feed.ts
- src/renderer/pages/home/news_feed/news_article/news_article.tsx
Here is how a Project Slippi post looks:
And then a repost:
> Bluesky Posts
